# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ECE385/ECE385_project/project.srcs/sources_1/bd/mb_pacman/ip/mb_pacman_dlmb_bram_if_cntlr_0/mb_pacman_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_pacman_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE385/ECE385_project/project.gen/sources_1/bd/mb_pacman/ip/mb_pacman_dlmb_bram_if_cntlr_0/mb_pacman_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pacman_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/ECE385/ECE385_project/project.srcs/sources_1/bd/mb_pacman/ip/mb_pacman_dlmb_bram_if_cntlr_0/mb_pacman_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_pacman_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ECE385/ECE385_project/project.gen/sources_1/bd/mb_pacman/ip/mb_pacman_dlmb_bram_if_cntlr_0/mb_pacman_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_pacman_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
