# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_pacman/mb_pacman.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman || ORIG_REF_NAME==mb_pacman} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_microblaze_0_0/mb_pacman_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_microblaze_0_0 || ORIG_REF_NAME==mb_pacman_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_dlmb_v10_0/mb_pacman_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_dlmb_v10_0 || ORIG_REF_NAME==mb_pacman_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_ilmb_v10_0/mb_pacman_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_ilmb_v10_0 || ORIG_REF_NAME==mb_pacman_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_dlmb_bram_if_cntlr_0/mb_pacman_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_pacman_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_ilmb_bram_if_cntlr_0/mb_pacman_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_pacman_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_lmb_bram_0/mb_pacman_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_lmb_bram_0 || ORIG_REF_NAME==mb_pacman_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_microblaze_0_axi_periph_0/mb_pacman_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_pacman_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_microblaze_0_axi_intc_0/mb_pacman_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_pacman_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_mdm_1_0/mb_pacman_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_mdm_1_0 || ORIG_REF_NAME==mb_pacman_mdm_1_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_clk_wiz_1_0/mb_pacman_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_clk_wiz_1_0 || ORIG_REF_NAME==mb_pacman_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_rst_clk_wiz_1_100M_0/mb_pacman_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_pacman_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_xbar_0/mb_pacman_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_xbar_0 || ORIG_REF_NAME==mb_pacman_xbar_0} -quiet] -quiet

# IP: bd/mb_pacman/ip/mb_pacman_axi_uartlite_0_0/mb_pacman_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_pacman_axi_uartlite_0_0 || ORIG_REF_NAME==mb_pacman_axi_uartlite_0_0} -quiet] -quiet

# XDC: e:/ECE385/ECE385_project/project.gen/sources_1/bd/mb_pacman/mb_pacman_ooc.xdc
